apiVersion: apps/v1
kind: Deployment
metadata:
  name: rgetre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rgetre
  template:
    metadata:
      labels:
        app: rgetre
    spec:
      containers:
      - image: okteto.dev/rgetre:latest
        name: rgetre
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "74b3dcc7-0df9-449b-93b6-46c5446831e6"
        - name: Vless_Path
          value: "/vl5uhgty"
        - name: Vmess_UUID
          value: "74b3dcc7-0df9-449b-93b6-46c5446831e6"
        - name: Vmess_Path
          value: "/vm6rfed"
        - name: Share_Path
          value: "/v2link"
